"""clone_structure_audit.py — did a declared repeat group actually get extracted.

`clone_structural_diff.py` pins "every measured element is in the render" and
`device_compare.py` pins "it looks like the original" — both fidelity axes.
Neither says anything about whether the generated Swift has structure: a feed
of 30 cards emitted as 30 independent absolute blocks scores perfectly on both
and is still not code anyone can edit. `clone_structure.py` detects the repeat
groups and `clone_view_codegen.py`'s `repeat_units()` extracts the confirmed
ones into a component + `ForEach` — but `repeat_units()` has silent skip paths
(an id claimed by an earlier group, a crop that dropped one, a group spanning
the scroll boundary), and a skipped group means the screen quietly reverted to
flat replay. These pin the rule: every declared group must appear as an
extracted component, or the screen fails.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "clone_structure_audit.py"
MARKER = "// Generated by clone_view_codegen.py"


def run_audit(root: Path, stem: str, view: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["python3", str(SCRIPT), str(root), stem, view],
        capture_output=True, text=True,
    )


class ClonestructureAuditCase(unittest.TestCase):
    def setUp(self):
        self._dir = tempfile.TemporaryDirectory()
        self.root = Path(self._dir.name)
        (self.root / "structure").mkdir()
        (self.root / "Sources").mkdir()
        self.addCleanup(self._dir.cleanup)

    def write_structure(self, stem: str, groups: list[dict]) -> None:
        payload = {"generated_by_clone_structure": True, "version": 1,
                   "source": f"screens/{stem}.json", "groups": groups}
        (self.root / "structure" / f"{stem}.json").write_text(
            json.dumps(payload), encoding="utf-8")

    def write_source(self, view: str, body: str, generated: bool = True) -> None:
        marker = f"{MARKER} from x. Hand edits are overwritten.\n" if generated else ""
        (self.root / "Sources" / f"{view}.swift").write_text(
            marker + body, encoding="utf-8")


class TestExtractedGroupPasses(ClonestructureAuditCase):
    def test_a_declared_group_that_was_extracted_passes(self):
        self.write_structure("01-feed", [
            {"parent": 0, "children": [1, 4, 7], "axis": "vertical",
             "pitch": 100.0, "count": 3, "component": "FeedItem"},
        ])
        self.write_source("FeedView", (
            "struct FeedView: View {\n"
            "    var body: some View { EmptyView() }\n"
            "}\n\n"
            "struct FeedItem: View {\n"
            "    let elements: [CloneElement]\n"
            "}\n"
        ))

        r = run_audit(self.root, "01-feed", "FeedView")

        self.assertEqual(r.returncode, 0, msg=r.stdout + r.stderr)
        self.assertIn("OK: 01-feed (FeedView) extracted all 1 declared repeat group(s)",
                      r.stdout)


class TestSkippedGroupFails(ClonestructureAuditCase):
    def test_a_declared_group_that_was_not_extracted_fails_and_is_named(self):
        # The structure draft confirms a group, but the generated file never
        # produced a `FeedItem` struct — exactly what `repeat_units()` does
        # when a crop drops one of the member ids and the subset check fails.
        self.write_structure("01-feed", [
            {"parent": 0, "children": [1, 4, 7], "axis": "vertical",
             "pitch": 100.0, "count": 3, "component": "FeedItem"},
        ])
        self.write_source("FeedView", (
            "struct FeedView: View {\n"
            "    var body: some View { EmptyView() }\n"
            "}\n"
        ))

        r = run_audit(self.root, "01-feed", "FeedView")

        self.assertEqual(r.returncode, 1, msg=r.stdout + r.stderr)
        self.assertIn("ERROR: 01-feed (FeedView)", r.stdout)
        self.assertIn("FeedItem", r.stdout)
        self.assertIn("did not extract 1", r.stdout)


class TestNoGroupsPasses(ClonestructureAuditCase):
    def test_a_screen_with_no_declared_groups_passes(self):
        # No structure/<stem>.json at all — the common case, a screen with
        # nothing repeating.
        self.write_source("PlainView", (
            "struct PlainView: View {\n"
            "    var body: some View { EmptyView() }\n"
            "}\n"
        ))

        r = run_audit(self.root, "02-plain", "PlainView")

        self.assertEqual(r.returncode, 0, msg=r.stdout + r.stderr)
        self.assertIn("OK: 02-plain declares no repeat group", r.stdout)

    def test_an_empty_groups_list_also_passes(self):
        self.write_structure("03-empty", [])
        self.write_source("EmptyGroupsView", "struct EmptyGroupsView: View {}\n")

        r = run_audit(self.root, "03-empty", "EmptyGroupsView")

        self.assertEqual(r.returncode, 0, msg=r.stdout + r.stderr)


class TestHandOwnedScreenIsExempt(ClonestructureAuditCase):
    def test_a_hand_owned_screen_is_exempt_even_missing_extraction(self):
        self.write_structure("01-feed", [
            {"parent": 0, "children": [1, 4, 7], "axis": "vertical",
             "pitch": 100.0, "count": 3, "component": "FeedItem"},
        ])
        # No MARKER — a person removed it and owns this file now.
        self.write_source("FeedView", (
            "struct FeedView: View {\n"
            "    var body: some View { EmptyView() }\n"
            "}\n"
        ), generated=False)

        r = run_audit(self.root, "01-feed", "FeedView")

        self.assertEqual(r.returncode, 0, msg=r.stdout + r.stderr)
        self.assertIn("OK: 01-feed (FeedView) is hand-owned", r.stdout)


class TestEdgeCases(ClonestructureAuditCase):
    def test_missing_generated_source_file_with_declared_groups_fails(self):
        self.write_structure("01-feed", [
            {"parent": 0, "children": [1, 4, 7], "axis": "vertical",
             "pitch": 100.0, "count": 3, "component": "FeedItem"},
        ])
        # Sources/FeedView.swift was never written.

        r = run_audit(self.root, "01-feed", "FeedView")

        self.assertEqual(r.returncode, 1, msg=r.stdout + r.stderr)
        self.assertIn("does not exist", r.stdout)

    def test_wrong_argument_count_is_a_usage_error(self):
        r = subprocess.run(["python3", str(SCRIPT), str(self.root)],
                           capture_output=True, text=True)
        self.assertEqual(r.returncode, 2)
        self.assertIn("usage", r.stderr)


if __name__ == "__main__":
    unittest.main()
