#!/usr/bin/env python3
"""clone_view_codegen.py — a measured first pass of every reproduced screen.

    clone_view_codegen.py <clone-root> [--flow flow.jsonl] [--views views.json]

Step 5 of the clone skill used to start from an empty placeholder per screen,
which made `verify` report the same thing for all of them: every element
missing. Authoring 30 screens of semantic SwiftUI by hand before the first
honest comparison is not a loop anyone finishes, and the dominant reproduction
failure is a wholesale MISSING element (DCGen, arXiv 2406.16386: 85.3%) — the
one failure the measurement can close mechanically.

So: emit one node per measured element, at its measured frame, with its
measured colour, text size and accessibility label. This is a replay of the
measurement, not idiomatic SwiftUI — it has no adaptive layout — but it is
faithful by construction and it is what a human then edits toward semantics.
Generated files carry the marker below and are the only ones this rewrites; a
screen you have taken over by hand is never clobbered.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
from pathlib import Path

_flow_codegen_spec = importlib.util.spec_from_file_location(
    "clone_flow_codegen", Path(__file__).resolve().parent / "clone_flow_codegen.py")
flow_codegen = importlib.util.module_from_spec(_flow_codegen_spec)
assert _flow_codegen_spec.loader is not None
_flow_codegen_spec.loader.exec_module(flow_codegen)

MARKER = "// Generated by clone_view_codegen.py"
STATE_MARKER = "clone-state:"
SYNTH_ID = "clone-action-synth:"
RUNTIME = "CloneRuntime.swift"


def _escape(text: str) -> str:
    """A Swift string literal body. Backslash first or it doubles the rest."""
    out = text.replace("\\", "\\\\").replace('"', '\\"')
    return out.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")


def _records(records: list[dict]) -> str:
    """The elements as a JSON array inside a Swift raw string literal.

    Not `[CloneElement(...), ...]`: Swift type-checks a large array literal of
    an initialiser with defaulted arguments in close to quadratic time, and one
    170-element screen took 13 seconds on its own — the whole build was minutes,
    which is the cost of every fix/re-measure round. A raw string literal
    compiles instantly and JSONDecoder reads it at launch. Measured 2026-08-23.
    """
    body = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
    # Three hashes: no escaped JSON can terminate the literal early.
    return f'###"{body}"###'


def _hex(value) -> str | None:
    if isinstance(value, str) and re.fullmatch(r"#[0-9A-Fa-f]{6}", value):
        return value.upper()
    return None


def _num(value, default: float = 0.0) -> float:
    try:
        return round(float(value), 1)
    except (TypeError, ValueError):
        return default


def crops_by_element(root: Path, stem: str) -> dict[int, str]:
    """Element index -> the capture crop extracted for it, for one screen.

    `clone_postprocess.py --extract-assets` already cut these out of the
    screenshot and recorded their provenance in assets/manifest.json; nothing
    was drawing them, so every measured image rendered as a flat rectangle of
    its average colour.
    """
    manifest = root / "assets" / "manifest.json"
    if not manifest.is_file():
        return {}
    try:
        entries = json.loads(manifest.read_text(encoding="utf-8")).get("assets") or []
    except (OSError, json.JSONDecodeError):
        return {}
    found: dict[int, tuple[str, dict | None]] = {}
    for entry in entries:
        source = str(entry.get("sourceMeasurement") or "")
        if Path(source).stem != stem:
            continue
        element = entry.get("element") or {}
        index, sha = element.get("index"), entry.get("sha256")
        if not (isinstance(index, int) and isinstance(sha, str) and sha):
            continue
        # Where the crop was actually cut from. An element can extend past the
        # screen — Threads' AdditionalDimmingOverlay is 615x286 starting at
        # x=-120 — and the crop is clamped to the capture. Stretching that back
        # over the whole frame magnified the pixels inside it, which is how a
        # 14pt line of the feed came out as a banner. Measured 2026-08-23.
        scale = entry.get("pointToPixelScale")
        box = entry.get("pixelBounds") or {}
        region = None
        try:
            if scale:
                region = {"x": round(float(box["x"]) / float(scale), 1),
                          "y": round(float(box["y"]) / float(scale), 1),
                          "width": round(float(box["width"]) / float(scale), 1),
                          "height": round(float(box["height"]) / float(scale), 1)}
        except (KeyError, TypeError, ValueError, ZeroDivisionError):
            region = None
        found[index] = (sha, region)
    return found


def uncovered_crops(root: Path, stem: str) -> list[tuple[str, dict]]:
    """(crop, frame) for the pixels no leaf element accounts for on this screen.

    Threads exposes a post avatar to no accessibility element at all, so the
    measurement cannot see it and the reproduction drew nothing there — a whole
    column of empty space next to every post. These come from the same capture
    crop path as the icons, with the same provenance.
    """
    manifest = root / "assets" / "manifest.json"
    if not manifest.is_file():
        return []
    try:
        entries = json.loads(manifest.read_text(encoding="utf-8")).get("assets") or []
    except (OSError, json.JSONDecodeError):
        return []
    found: list[tuple[str, dict]] = []
    for entry in entries:
        if Path(str(entry.get("sourceMeasurement") or "")).stem != stem:
            continue
        element = entry.get("element") or {}
        if element.get("role") != "uncoveredRegion":
            continue
        sha, frame = entry.get("sha256"), element.get("frame")
        if isinstance(sha, str) and sha and isinstance(frame, dict):
            found.append((sha, frame))
    return found


ORPHAN_SHARD_MAX_PT = 32.0
_WITNESS_AREA_FRACTION = 0.25


def drop_orphan_shards(uncovered: list[tuple[str, dict]],
                       measurement: dict) -> list[tuple[str, dict]]:
    """Uncovered crops minus the text shards a modal leaves behind.

    When a sheet is up, iOS hides everything behind it from the accessibility
    tree, so the background feed has no measured elements at all — and the
    uncovered-region pass then slices its running text into glyph-sized crops.
    Painted back, those read as a layout bug, worse than the empty region they
    replace (measured 2026-08-23: Threads' post-options sheet shipped shards of
    "87", "열심", "점프" from the post behind it, and the structural diff still
    said every spec element was present).

    A crop earns its place when it is bigger than a glyph, or when some measured
    element overlaps it — an icon or avatar sitting inside a real control.
    Witnesses come from the measurement (screen coordinates, pre-scroll-rebase),
    because comparing against rebased literals mixes coordinate spaces and
    quietly marks every shard as witnessed. Full-bleed wrappers overlap
    everything, so they witness nothing.
    """
    elements = measurement.get("elements") or []
    points = (measurement.get("screen") or {}).get("points") or {}
    area_limit = (_num(points.get("width"), 375.0)
                  * _num(points.get("height"), 812.0) * _WITNESS_AREA_FRACTION)
    witnesses = []
    for element in elements:
        if not ((element.get("label") or "").strip() or element.get("text")):
            continue
        frame = element.get("frame") or {}
        w, h = _num(frame.get("width")), _num(frame.get("height"))
        if w * h < area_limit:
            witnesses.append((_num(frame.get("x")), _num(frame.get("y")), w, h))
    kept = []
    for sha, frame in uncovered:
        x, y = _num(frame.get("x")), _num(frame.get("y"))
        w, h = _num(frame.get("width")), _num(frame.get("height"))
        if w > ORPHAN_SHARD_MAX_PT or h > ORPHAN_SHARD_MAX_PT or any(
                x < wx + ww and wx < x + w and y < wy + wh and wy < y + h
                for wx, wy, ww, wh in witnesses):
            kept.append((sha, frame))
    return kept


SCROLL_ROLES = {"AXScrollView", "AXCollectionView", "AXTable"}


def scroll_container(measurement: dict) -> tuple[dict | None, set[int]]:
    """The screen's main scrollable area and the elements inside it.

    A replayed screen is a fixed stack, so a swipe does nothing at all — the
    reproduction reads as broken before anyone looks at a colour. The
    accessibility tree already separates the chrome from the scrolling content
    (Threads' top bar and tab bar are NOT descendants of its feed), so the two
    can be rendered as what they are.
    """
    elements = measurement.get("elements") or []
    children: dict[int, list[int]] = {}
    for index, element in enumerate(elements):
        children.setdefault(element.get("parent"), []).append(index)

    def descendants(index: int) -> set[int]:
        found: set[int] = set()
        stack = list(children.get(index, []))
        while stack:
            node = stack.pop()
            found.add(node)
            stack.extend(children.get(node, []))
        return found

    candidates = [(_num(element["frame"].get("width")) * _num(element["frame"].get("height")), index)
                  for index, element in enumerate(elements)
                  if element.get("role") in SCROLL_ROLES and element.get("frame")]
    if not candidates:
        return None, set()
    _area, index = max(candidates)
    inside = descendants(index)
    if not inside:
        return None, set()
    frame = elements[index]["frame"]
    bottom = max(_num(elements[i]["frame"].get("y")) + _num(elements[i]["frame"].get("height"))
                 for i in inside)
    box = {
        "x": _num(frame.get("x")), "y": _num(frame.get("y")),
        "w": _num(frame.get("width")), "h": _num(frame.get("height")),
        # Never smaller than the viewport, or the scroll view has nothing to do.
        # Vertical only: `right` overshoots because of overlays that bleed past
        # the screen, and a sideways scroll the original never had reads as a bug.
        "cw": _num(frame.get("width")),
        "ch": max(_num(frame.get("height")), round(bottom - _num(frame.get("y")), 1)),
    }
    return box, inside


def element_literals(measurement: dict, actions: set[str],
                     points: dict[str, tuple[float, float]] | None = None,
                     crops: dict[int, str] | None = None,
                     uncovered: list[tuple[str, dict]] | None = None,
                     scroll: tuple[dict | None, set[int]] = (None, set())) -> list[dict]:
    """One `CloneElement(...)` literal per measured element, in paint order.

    The measurement lists elements depth-first, parents before children, which
    is also the order the original composites them — so emitting in list order
    puts children on top of their own container without a z-index.
    """
    background = _hex(((measurement.get("palette") or [{}])[0]).get("hex")) or "#000000"
    elements = measurement.get("elements") or []
    # The same label repeats down a container chain — Threads' feed has five
    # elements labelled "게시 옵션" at one frame. Only the LAST of them carries
    # the action: it is the topmost in paint order, so the tap reaches it, and
    # one tappable element per label is what lets a driver address it at all.
    last_for = {}
    for index, element in enumerate(elements):
        label = (element.get("label") or "").strip()
        if label:
            last_for[label] = index
    # Drawing a control's own label as text was tried and measured on
    # 2026-08-23: no pixel gain (-0.08pt mean over 28 screens) and it wrote
    # accessibility prose across icons — Threads labels a 37x34pt heart
    # "좋아요. 226명이 이 게시물을 좋아합니다.". Containing that needed three
    # more heuristics (box capacity, an assumed type size, an image guard) for
    # nothing, and every string it seemed to add is already drawn from a
    # measured AXStaticText on the same screen. Only measured type is drawn.
    last_for: dict[str, int] = {}
    for index, element in enumerate(elements):
        label = (element.get("label") or "").strip()
        if label:
            last_for[label] = index

    literals = []
    for index, element in enumerate(elements):
        frame = element.get("frame") or {}
        label = (element.get("label") or "").strip()
        colors = element.get("colors") or {}
        text_info = element.get("text") or {}
        parts = {
            "id": index,
            "x": _num(frame.get("x")), "y": _num(frame.get("y")),
            "w": _num(frame.get("width")), "h": _num(frame.get("height")),
            "label": label,
        }
        if text_info:
            # Only AXStaticText carries measured type. A button whose label
            # repeats its child text would otherwise be drawn twice.
            parts["text"] = label
            parts["size"] = _num(text_info.get("estimatedPointSize"), 14.0)
            foreground = _hex(colors.get("foreground")) or _hex(colors.get("center"))
            if foreground:
                parts["fg"] = foreground
        else:
            fill = _hex(colors.get("fill"))
            # A container whose fill is the screen background paints nothing —
            # filling it would just cover whatever was drawn before it.
            if fill and fill != background:
                parts["fill"] = fill
        crop = (crops or {}).get(index)
        if label and label in actions and index == last_for.get(label):
            parts["action"] = label
        box, inside = scroll
        if box and index in inside:
            # Inside the scroll view the origin is the container, not the screen.
            parts["scroll"] = 1
            parts["x"] = round(parts["x"] - box["x"], 1)
            parts["y"] = round(parts["y"] - box["y"], 1)
        literals.append(parts)
        if crop:
            # The picture is its own record at the region it was cut from, right
            # after the element it belongs to so paint order is unchanged. The
            # element keeps its label and frame for the structural diff.
            sha, region = crop
            region = region or {"x": parts["x"], "y": parts["y"],
                                "width": parts["w"], "height": parts["h"]}
            picture = {
                "id": len(elements) + 20000 + index,
                "x": _num(region.get("x")), "y": _num(region.get("y")),
                "w": _num(region.get("width")), "h": _num(region.get("height")),
                "label": "", "asset": sha,
            }
            if parts.get("scroll"):
                picture["scroll"] = 1
                picture["x"] = round(picture["x"] - box["x"], 1)
                picture["y"] = round(picture["y"] - box["y"], 1)
            literals.append(picture)
    for offset, (sha, frame) in enumerate(
            drop_orphan_shards(uncovered or [], measurement)):
        literals.append({
            "id": len(elements) + 10000 + offset,
            "x": _num(frame.get("x")), "y": _num(frame.get("y")),
            "w": _num(frame.get("width")), "h": _num(frame.get("height")),
            "label": "", "asset": sha,
        })
    # An observed action whose label is nowhere in this capture. A live feed is
    # different content every time it is captured, so a post the run tapped is
    # often absent from the measurement the screen is reproduced from — and the
    # reproduction then has nothing to tap at all (measured 2026-08-23: 4 of 42
    # transitions). The tap coordinate was recorded with the transition, so put
    # a target back where the original one was.
    synthetic: list[dict] = []
    for offset, label in enumerate(sorted(actions - set(last_for))):
        point = (points or {}).get(label)
        if point is None:
            continue
        synthetic.append({
            "id": len(elements) + offset,
            "x": round(point[0] - 22, 1), "y": round(point[1] - 22, 1),
            "w": 44.0, "h": 44.0,
            "label": label, "action": label, "synthetic": True,
        })
    # Two synthesised targets on top of each other — recorded tap points from
    # different captures of a feed whose rows moved — cannot both be tapped:
    # whichever is drawn last wins and the other is dead, and neither matches
    # the capture anyway. Drop the pair rather than guess (Codex review
    # 2026-08-23; measured: item_archive_ and melody_ykaaa at the same 44pt box).
    def overlapping(a: dict, b: dict) -> bool:
        return (abs(a["x"] - b["x"]) < 22 and abs(a["y"] - b["y"]) < 22)
    clashing = {i for i, a in enumerate(synthetic) for j, b in enumerate(synthetic)
                if i != j and overlapping(a, b)}
    literals.extend(t for i, t in enumerate(synthetic) if i not in clashing)
    return literals


def confirmed_groups(root: Path, stem: str) -> list[dict]:
    """The repeat groups declared for one screen, machine-drafted or hand-owned.

    Missing, unreadable or empty all mean the same thing here — no claim — and
    the generator falls back to the flat replay rather than inventing structure.
    """
    path = root / "structure" / f"{stem}.json"
    if not path.is_file():
        return []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        print(f"WARN: ignoring unreadable {path}: {exc}", file=sys.stderr)
        return []
    groups = payload.get("groups") if isinstance(payload, dict) else None
    return [g for g in groups if isinstance(g, dict)] if isinstance(groups, list) else []


def _subtree_ids(measurement: dict, index: int) -> set[int]:
    """Every element id under `index`, inclusive."""
    children: dict[int, list[int]] = {}
    for position, element in enumerate(measurement.get("elements") or []):
        parent = element.get("parent", -1)
        if isinstance(parent, int) and parent >= 0:
            children.setdefault(parent, []).append(position)
    found, stack = set(), [index]
    while stack:
        at = stack.pop()
        if at in found:
            continue
        found.add(at)
        stack.extend(children.get(at, []))
    return found


def _lower_camel(name: str) -> str:
    return name[:1].lower() + name[1:] if name else name


def repeat_units(measurement: dict, literals: list[dict],
                 groups: list[dict]) -> tuple[list[dict], list[dict]]:
    """Split the flat replay into (what stays flat, one unit per confirmed group).

    The replay is faithful and unreadable: thirty cards are thirty independent
    blocks, and no amount of pixel work turns that into something a person can
    edit. A confirmed repeat says which blocks are one unit, and this is where
    that claim becomes a type instead of a note.

    Element ids are preserved across the move — a restructuring that drops an
    element would trade the readability problem for the dominant reproduction
    failure, which is a bad trade at any price.
    """
    by_id = {literal["id"]: literal for literal in literals if "id" in literal}
    taken: set[int] = set()
    units: list[dict] = []
    for group in groups:
        component = group.get("component")
        members = group.get("children") or []
        if not component or len(members) < 2:
            continue
        subtrees = [sorted(_subtree_ids(measurement, member)) for member in members]
        ids = {i for subtree in subtrees for i in subtree}
        # A group whose ids are not all present (a crop dropped one, another
        # group already claimed them) is left flat rather than emitted half.
        if ids & taken or not ids <= set(by_id):
            continue
        scrolls = {by_id[i].get("scroll") for i in ids}
        if len(scrolls) > 1:
            continue          # spans the scroll boundary — not one unit
        items = []
        for member, subtree in zip(members, subtrees):
            origin = by_id[member]
            items.append({
                "origin": (origin["x"], origin["y"]),
                "literals": [{**by_id[i], "x": round(by_id[i]["x"] - origin["x"], 1),
                              "y": round(by_id[i]["y"] - origin["y"], 1)}
                             for i in subtree],
            })
        units.append({
            "component": component,
            "scroll": next(iter(scrolls)),
            "width": by_id[members[0]]["w"],
            "height": by_id[members[0]]["h"],
            "items": items,
        })
        taken |= ids
    remaining = [literal for literal in literals
                 if literal.get("id") not in taken]
    return remaining, units


def _unit_storage(unit: dict) -> str:
    handle = _lower_camel(unit["component"])
    blobs = ",\n        ".join(f"cloneElements({_records(item['literals'])})"
                               for item in unit["items"])
    origins = ", ".join(f"CGPoint(x: {item['origin'][0]}, y: {item['origin'][1]})"
                        for item in unit["items"])
    return (f"    private static let {handle}Items: [[CloneElement]] = [\n"
            f"        {blobs},\n    ]\n"
            f"    private static let {handle}Origins: [CGPoint] = [{origins}]\n")


def _unit_body(unit: dict, indent: str) -> str:
    handle = _lower_camel(unit["component"])
    return (f"{indent}ForEach(Array(Self.{handle}Items.enumerated()), id: \\.offset) "
            f"{{ index, item in\n"
            f"{indent}    {unit['component']}(elements: item, onAction: onAction)\n"
            f"{indent}        .offset(x: Self.{handle}Origins[index].x,\n"
            f"{indent}                y: Self.{handle}Origins[index].y)\n"
            f"{indent}}}\n")


def _unit_struct(unit: dict) -> str:
    return f"""

/// One repeated unit, extracted from a confirmed structure group. Edit it once
/// and every instance follows — that is the whole reason it exists.
struct {unit['component']}: View {{
    let elements: [CloneElement]
    var onAction: (String) -> Void = {{ _ in }}

    var body: some View {{
        ZStack(alignment: .topLeading) {{
            ForEach(elements) {{ element in
                CloneElementView(element: element)
            }}
            CloneActionLayer(elements: elements, onAction: onAction)
        }}
        .frame(width: {unit['width']}, height: {unit['height']}, alignment: .topLeading)
    }}
}}"""


def render_view(name: str, measurement: dict, actions: set[str], source: str,
                state: str, points: dict[str, tuple[float, float]] | None = None,
                crops: dict[int, str] | None = None,
                uncovered: list[tuple[str, dict]] | None = None,
                groups: list[dict] | None = None) -> str:
    # Not `points` — that name is the tap coordinates parameter, and shadowing
    # it silently dropped every synthesised target.
    logical = (measurement.get("screen") or {}).get("points") or {}
    width, height = _num(logical.get("width"), 375.0), _num(logical.get("height"), 812.0)
    background = _hex(((measurement.get("palette") or [{}])[0]).get("hex")) or "#000000"
    scroll = scroll_container(measurement)
    literals = element_literals(measurement, actions, points, crops, uncovered, scroll)
    # No confirmed group means no restructuring and a byte-identical file: the
    # extraction is opt-in on evidence, never on the generator's own guess.
    literals, units = repeat_units(measurement, literals, groups or [])
    body = _records(literals)
    storage = "".join(_unit_storage(unit) for unit in units)
    structs = "".join(_unit_struct(unit) for unit in units)
    scroll_units = "".join(_unit_body(u, " " * 20) for u in units if u["scroll"] == 1)
    chrome_units = "".join(_unit_body(u, " " * 12) for u in units if u["scroll"] != 1)
    box = scroll[0]
    scroll_drag = "" if not box else (
        f"        .modifier(CloneScrollDrag(offset: $scrollOffset, "
        f"maxOffset: {max(0.0, round(box['ch'] - box['h'], 1))}))\n")
    # The scrolling content is drawn first and the chrome over it, which is the
    # order the tree already reports — Threads' top bar and tab bar come after
    # its feed and float above it.
    # Written with single braces on purpose: this string is INSERTED into the
    # template below, not re-processed by it, so doubling them would ship `{{`.
    scroll_body = "" if not box else f"""            CloneScrollArea(viewport: CGSize(width: {box['w']}, height: {box['h']}),
                            content: CGSize(width: {box['cw']}, height: {box['ch']}),
                            offset: $scrollOffset) {{
                ZStack(alignment: .topLeading) {{
                    ForEach(Self.elements.filter {{ $0.scroll == 1 }}) {{ element in
                        CloneElementView(element: element)
                    }}
{scroll_units}
                    CloneActionLayer(elements: Self.elements.filter {{ $0.scroll == 1 }},
                                     onAction: onAction)
                }}
                .frame(width: {box['cw']}, height: {box['ch']}, alignment: .topLeading)
            }}
            .offset(x: {box['x']}, y: {box['y']})
"""
    return f"""{MARKER} from {source}. Hand edits are overwritten — delete
// the marker line above to take this screen over.
import SwiftUI

struct {name}: View {{
    var onAction: (String) -> Void = {{ _ in }}
    @State private var scrollOffset: CGFloat = 0

    private static let elements: [CloneElement] = cloneElements({body})
{storage}
    var body: some View {{
        ZStack(alignment: .topLeading) {{
            cloneColor("{background}")
            // Which screen the router is actually showing, readable from the
            // accessibility tree. `clone_functional.py` walks the observed
            // transitions and has no other way to ask.
            Color.clear.frame(width: 1, height: 1)
                .accessibilityElement()
                .accessibilityLabel("{STATE_MARKER}{state}")
{scroll_body}            ForEach(Self.elements.filter {{ $0.scroll != 1 }}) {{ element in
                CloneElementView(element: element)
            }}
{chrome_units}
            CloneActionLayer(elements: Self.elements.filter {{ $0.scroll != 1 }},
                             onAction: onAction)
        }}
        .frame(width: {width}, height: {height}, alignment: .topLeading)
{scroll_drag}        // The measurements are points on the device that was observed. On any
        // other screen size the replay is scaled to fit, not re-laid-out: it is
        // a measured replica, and stretching it would be a different screen.
        .cloneFitted(width: {width}, height: {height})
        // Without this the root view is laid out INSIDE the safe area and every
        // measured y lands 8pt low — exactly the structural tolerance, so each
        // screen sat on the edge of "moved". Measured 2026-08-23.
        .ignoresSafeArea()
        .preferredColorScheme(.dark)
    }}
}}{structs}
"""


def render_stub(name: str, state: str,
                actions: set[str] | None = None,
                points: dict[str, tuple[float, float]] | None = None) -> str:
    """A screen that is mapped but not measured yet.

    Loud on screen rather than blank: `verify` reports it as unverifiable, and
    anyone who renders it sees why instead of a black rectangle.
    """
    targets = []
    for offset, label in enumerate(sorted(actions or set())):
        point = (points or {}).get(label)
        if point is None:
            continue
        targets.append({
            "id": offset, "x": round(point[0] - 22, 1), "y": round(point[1] - 22, 1),
            "w": 44.0, "h": 44.0,
            "label": label, "action": label, "synthetic": True,
        })
    body = _records(targets)
    return f"""{MARKER} — no measurement for state {state}.
import SwiftUI

struct {name}: View {{
    var onAction: (String) -> Void = {{ _ in }}

    // No picture, but the transitions out of this screen were observed and
    // their tap points recorded — so the flow still works through it.
    private static let elements: [CloneElement] = cloneElements({body})

    var body: some View {{
        ZStack(alignment: .topLeading) {{
            Color.black.ignoresSafeArea()
            // Same marker as a generated screen: without it the functional walk
            // reads "None" here and blames the transition that led to it.
            Color.clear.frame(width: 1, height: 1)
                .accessibilityElement()
                .accessibilityLabel("{STATE_MARKER}{state}")
            Text("no measurement for {state}").foregroundStyle(.red)
            CloneActionLayer(elements: Self.elements, onAction: onAction)
        }}
        .ignoresSafeArea()
        .preferredColorScheme(.dark)
    }}
}}
"""


RUNTIME_SOURCE = f"""{MARKER}
import SwiftUI

let CLONE_ACTION_ID = "clone-action:"
let CLONE_SYNTH_ID = "clone-action-synth:"
let CLONE_MIN_TAP: CGFloat = 44

/// One measured element, replayed at its measured frame.
///
/// Every optional field really is optional so a missing JSON key decodes rather
/// than throwing — the generator omits whatever a given element does not have.
struct CloneElement: Identifiable, Decodable {{
    let id: Int
    let x: CGFloat
    let y: CGFloat
    let w: CGFloat
    let h: CGFloat
    let label: String
    var text: String? = nil
    var size: CGFloat? = nil
    var fg: String? = nil
    var fill: String? = nil
    /// A capture crop shipped in the app bundle, by content hash. Research-only
    /// provenance is recorded in .autobot/clone/assets/manifest.json.
    var asset: String? = nil
    var action: String? = nil
    /// 1 when this element rides inside the screen's scroll view. Its x/y are
    /// then relative to that container, not to the screen.
    var scroll: Int? = nil
    /// True when the label was not in the capture this screen is reproduced
    /// from and the target was placed at the tap point recorded on the device.
    var synthetic: Bool? = nil
}}

/// Decode a screen's elements. A screen that cannot be read renders empty,
/// which the structural diff reports as every element missing — loud, not silent.
func cloneElements(_ json: String) -> [CloneElement] {{
    guard let data = json.data(using: .utf8),
          let decoded = try? JSONDecoder().decode([CloneElement].self, from: data)
    else {{ return [] }}
    return decoded
}}

/// A capture crop from the app bundle, or nil when none was extracted.
func cloneImage(_ name: String?) -> UIImage? {{
    guard let name else {{ return nil }}
    // Two layouts, one lookup: device_render.sh copies the crops flat into the
    // .app, while the device project ships them in a synchronized folder.
    let url = Bundle.main.url(forResource: name, withExtension: "png")
        ?? Bundle.main.url(forResource: name, withExtension: "png", subdirectory: "Crops")
    guard let url else {{ return nil }}
    return UIImage(contentsOfFile: url.path)
}}

func cloneColor(_ hex: String?) -> Color {{
    guard let hex, hex.count == 7 else {{ return .clear }}
    let digits = hex.dropFirst()
    guard let value = UInt32(digits, radix: 16) else {{ return .clear }}
    return Color(red: Double((value >> 16) & 0xFF) / 255,
                 green: Double((value >> 8) & 0xFF) / 255,
                 blue: Double(value & 0xFF) / 255)
}}

/// The tap targets, drawn above the replay.
///
/// Separate from the picture on purpose: only labels this run actually saw move
/// the app are here, one target per label, nothing overlapping them.
struct CloneActionLayer: View {{
    let elements: [CloneElement]
    var onAction: (String) -> Void = {{ _ in }}

    var body: some View {{
        ForEach(elements.filter {{ $0.action != nil }}) {{ element in
            // Grown to the 44pt HIG minimum around the measured centre. The
            // originals are often smaller than a touch can reliably land on —
            // a 3pt close handle, an 18pt overflow dot — and measured
            // 2026-08-23 those were exactly the targets no tap ever reached,
            // while every target 23pt or larger worked. 28pt was not enough;
            // 44 is. The layer is transparent, so the screen looks the same.
            let width = max(element.w, CLONE_MIN_TAP)
            let height = max(element.h, CLONE_MIN_TAP)
            Color.clear
                .frame(width: width, height: height)
                .contentShape(Rectangle())
                .accessibilityElement()
                .accessibilityLabel(element.label)
                .accessibilityIdentifier(((element.synthetic ?? false) ? CLONE_SYNTH_ID : CLONE_ACTION_ID)
                                         + (element.action ?? ""))
                .offset(x: element.x + (element.w - width) / 2,
                        y: element.y + (element.h - height) / 2)
                .onTapGesture {{ onAction(element.action ?? "") }}
        }}
    }}
}}

/// A scrolling region that keeps hit-testing inside SwiftUI.
///
/// Not a `ScrollView`: on the iOS 26 simulator a `ScrollView` placed under
/// fixed chrome in a `ZStack` swallowed taps on that chrome near the top and
/// bottom of the screen — tab bar and top bar, exactly the controls a clone
/// needs most. Measured 2026-08-23 with a four-target probe; `.zIndex`,
/// `.overlay`, `Button`, `highPriorityGesture`, `.ignoresSafeArea` and
/// `.scrollEdgeEffectHidden` all left it that way.
///
/// And no gesture of its own: a drag gesture attached HERE — a full-screen
/// sibling drawn under the chrome — stole the chrome's taps just the same
/// (measured: remove the gesture and the tab bar works again). The gesture
/// lives on the screen root, an ANCESTOR of every target, where a
/// `simultaneousGesture` composes with the children's taps instead of
/// competing with them. This view only shows the content at the offset it is
/// handed. Deliberately plain: clamped, no momentum.
struct CloneScrollArea<Content: View>: View {{
    let viewport: CGSize
    let content: CGSize
    @Binding var offset: CGFloat
    @ViewBuilder let body_: () -> Content

    init(viewport: CGSize, content: CGSize, offset: Binding<CGFloat>,
         @ViewBuilder content body: @escaping () -> Content) {{
        self.viewport = viewport
        self.content = content
        self._offset = offset
        self.body_ = body
    }}

    var body: some View {{
        body_()
            .offset(y: -offset)
            .frame(width: viewport.width, height: viewport.height, alignment: .topLeading)
            .clipped()
            .accessibilityElement(children: .contain)
            .accessibilityLabel("clone-scroll")
    }}
}}

/// The drag that scrolls a screen. Attached to the screen root so it composes
/// with every target's tap instead of competing with it (see CloneScrollArea).
struct CloneScrollDrag: ViewModifier {{
    @Binding var offset: CGFloat
    let maxOffset: CGFloat
    @State private var dragStart: CGFloat = 0

    func body(content: Content) -> some View {{
        content.simultaneousGesture(
            DragGesture(minimumDistance: 8)
                .onChanged {{ value in
                    offset = min(maxOffset, max(0, dragStart - value.translation.height))
                }}
                .onEnded {{ _ in dragStart = offset }}
        )
    }}
}}

/// Fit a fixed-size measured canvas into whatever screen it is shown on.
///
/// Same-size screens (the device the measurement came from, or its simulator)
/// get the identity, so renders stay byte-comparable. Anything else gets
/// uniform scaling about the top-left — the canvas keeps its aspect and is
/// centred on the longer axis.
extension View {{
    func cloneFitted(width: CGFloat, height: CGFloat) -> some View {{
        GeometryReader {{ proxy in
            let scale = min(proxy.size.width / width, proxy.size.height / height)
            let fitted = abs(scale - 1) < 0.001 ? 1 : scale
            self
                .frame(width: width, height: height, alignment: .topLeading)
                .scaleEffect(fitted, anchor: .topLeading)
                .frame(width: width * fitted, height: height * fitted, alignment: .topLeading)
                .position(x: proxy.size.width / 2, y: proxy.size.height / 2)
        }}
    }}
}}

struct CloneElementView: View {{
    let element: CloneElement
    var onAction: (String) -> Void = {{ _ in }}

    var body: some View {{
        content
            .frame(width: element.w, height: element.h)
            .clipped()
            // A decorative view is not in the accessibility tree at all, so the
            // structural diff would read every one of them as a missing
            // element. Measured against `axe describe-ui` 2026-08-23.
            .accessibilityElement()
            .accessibilityLabel(element.label)
            // AXUniqueId. Without it a driver asked to tap a repeated label
            // gets "multiple elements matched ... none expose AXUniqueId" and
            // refuses — measured against AXe 1.7.1, 2026-08-23.
            .accessibilityIdentifier("clone-el-\\(element.id)")
            .offset(x: element.x, y: element.y)
            // The replay is a picture. Interaction lives in CloneActionLayer,
            // drawn above it — trying to make 166 stacked, overlapping replayed
            // elements individually tappable produced controls that the
            // accessibility tree placed correctly and no touch could reach
            // (measured 2026-08-23).
            .allowsHitTesting(false)
    }}

    @ViewBuilder private var content: some View {{
        ZStack {{
            if let fill = element.fill {{
                Rectangle().fill(cloneColor(fill))
            }}
            if let image = cloneImage(element.asset) {{
                // .resizable() alone, no aspect fit or fill: the crop was cut at
                // exactly this element's frame, so stretching it to the frame is
                // the identity. scaledToFill overflowed the box and the overflow
                // GREW the frame the accessibility tree reports (228pt tall
                // became 286), which read as a missing element on three screens
                // — measured 2026-08-23.
                Image(uiImage: image).resizable()
            }}
            if let text = element.text {{
                Text(text)
                    .font(.system(size: element.size ?? 14))
                    .foregroundStyle(cloneColor(element.fg))
                    .lineLimit(max(1, Int((element.h / ((element.size ?? 14) * 1.3)).rounded())))
                    .truncationMode(.tail)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }}
            if element.fill == nil && element.text == nil {{
                Color.clear.contentShape(Rectangle())
            }}
        }}
    }}
}}
"""


def _measurement_labels(path: Path) -> set[str]:
    try:
        measurement = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return set()
    return {(element.get("label") or "").strip()
            for element in measurement.get("elements") or []}


def captures_by_state(flow: Path, screens: Path) -> dict[str, list[str]]:
    """Every measurement captured for each state, in the order it was taken.

    Read through ``flow_codegen.load_flow`` so declared state aliases apply
    here too. Parsing the log a second time by hand is how this file would
    otherwise key captures by a state the router no longer knows about.
    """
    captures: dict[str, list[str]] = {}
    for event in flow_codegen.load_flow(flow):
        if event.get("type") != "screen":
            continue
        for key in ("statekey", "state", "node"):
            state = event.get(key)
            if state and state != "?":
                name = str(event.get("name") or "")
                if name and (screens / f"{name}.json").is_file():
                    stems = captures.setdefault(state, [])
                    if name not in stems:
                        stems.append(name)
                break
    return captures


def state_to_stem(flow: Path, screens: Path,
                  actions: dict[str, set[str]] | None = None) -> dict[str, str]:
    """The capture to reproduce each state from.

    Not simply the first one. A state is captured several times and a live feed
    is different content each time, so the labels the run actually tapped are
    often absent from the first capture — and a view generated from it has no
    element to tap, which the functional walk reports as "no element with that
    label" (measured 2026-08-23: 7 of 42 transitions). Pick the capture that
    carries the most of this state's observed action labels; ties keep the
    earliest, so a state with no transitions behaves exactly as before.
    """
    captures = captures_by_state(flow, screens)
    actions = actions or {}
    chosen: dict[str, str] = {}
    for state, stems in captures.items():
        wanted = actions.get(state) or set()
        if not wanted or len(stems) == 1:
            chosen[state] = stems[0]
            continue
        def rank(stem: str) -> tuple[int, int, int]:
            labels = _measurement_labels(screens / f"{stem}.json")
            # Richest capture first. A feed captured mid-scroll has the same
            # state key and half the elements, and reproducing that one makes
            # the screen look emptier than it is — measured 2026-08-23, choosing
            # by action coverage alone took an 84-element capture over a
            # 166-element one and the pixel mismatch went 15.5% -> 21.7%.
            # An action label the chosen capture lacks still gets a target at
            # its recorded tap point, so coverage is only the tie-break.
            return (len(labels), len(wanted & labels), -stems.index(stem))

        chosen[state] = max(stems, key=rank)
    return chosen


def tap_points(flow: Path) -> dict[tuple[str, str], tuple[float, float]]:
    """Where on screen each observed action was tapped, per originating state."""
    points: dict[tuple[str, str], tuple[float, float]] = {}
    for event in flow_codegen.load_flow(flow):
        if event.get("type") != "tap":
            continue
        source = event.get("from_statekey") or event.get("from_state") or event.get("from")
        label = event.get("label")
        try:
            point = (float(event["x"]), float(event["y"]))
        except (KeyError, TypeError, ValueError):
            continue
        if source and label:
            points.setdefault((str(source), str(label)), point)
    return points


def transitions_by_state(flow: Path) -> dict[str, set[str]]:
    """Labels the router will act on, per originating state.

    Delegated to clone_flow_codegen on purpose: that module is what generates
    ObservedFlow.swift, so importing its extraction is the only way these taps
    are guaranteed to be the same keys the router dispatches on. Re-deriving
    them here is how this file first shipped reading `type == "action"` while
    the producer writes `type == "tap"` — the drift this repo has now recorded
    three times.
    """
    events = flow_codegen.load_flow(flow)
    captured = set(flow_codegen.captured_states(events))
    screens = flow.parent / "screens"
    observed, inferred = flow_codegen.all_transitions(
        events, captured, screens if screens.is_dir() else None)
    actions: dict[str, set[str]] = {}
    for source, action, _destination in observed + inferred:
        actions.setdefault(source, set()).add(action)
    return actions


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", help=".autobot/clone")
    parser.add_argument("--flow", default=None)
    parser.add_argument("--views", default=None)
    parser.add_argument("--pairs", action="store_true",
                        help="print the state->measurement->view join and exit. "
                             "The comparison must use the capture the view was "
                             "GENERATED from; a second implementation of this "
                             "join silently compares a screen against a "
                             "different capture of itself.")
    args = parser.parse_args(argv[1:])

    root = Path(args.root)
    flow = Path(args.flow) if args.flow else root / "flow.jsonl"
    views_path = Path(args.views) if args.views else root / "views.json"
    screens, sources = root / "screens", root / "Sources"
    for path in (flow, views_path, screens):
        if not path.exists():
            print(f"ERROR: no {path} — run 'clone_run.sh observe' first", file=sys.stderr)
            return 1
    sources.mkdir(parents=True, exist_ok=True)

    views = json.loads(views_path.read_text(encoding="utf-8")).get("views", {})
    actions = transitions_by_state(flow)
    points = tap_points(flow)
    stems = state_to_stem(flow, screens, actions)

    if args.pairs:
        for state, view in sorted(views.items()):
            stem = stems.get(state)
            print(f"PAIR {stem} {view}" if stem else f"UNPAIRED {state} {view}")
        return 0

    (sources / RUNTIME).write_text(RUNTIME_SOURCE, encoding="utf-8")
    written, kept, unmeasured, asset_backed = 0, [], [], 0
    for state, view in sorted(views.items()):
        target = sources / f"{view}.swift"
        if target.exists() and MARKER not in target.read_text(encoding="utf-8"):
            kept.append(view)
            continue
        stem = stems.get(state)
        if not stem:
            # Still emit the type: device_render.sh compiles Sources/ as one
            # unit and the generated router names every mapped view, so a type
            # that does not exist fails the build for every OTHER screen too.
            unmeasured.append(f"{state} ({view})")
            target.write_text(
                render_stub(view, state, actions.get(state, set()),
                            {label: point for (source, label), point in points.items()
                             if source == state}),
                encoding="utf-8")
            continue
        measurement = json.loads((screens / f"{stem}.json").read_text(encoding="utf-8"))
        asset_backed += len(crops_by_element(root, stem))
        target.write_text(
            render_view(view, measurement, actions.get(state, set()),
                        f"screens/{stem}.json", state,
                        {label: point for (source, label), point in points.items()
                         if source == state},
                        crops_by_element(root, stem),
                        uncovered_crops(root, stem),
                        confirmed_groups(root, stem)),
            encoding="utf-8")
        written += 1

    synthesised = sorted(
        f"{state}/{label}"
        for state, labels in actions.items()
        for label in labels
        if state in stems
        and label not in _measurement_labels(screens / f"{stems[state]}.json"))
    print(f"OK: generated {written} view(s) into {sources}")
    if asset_backed:
        # Accounting, not decoration: these regions are pixels cut from the
        # original screenshot, so a pixel score over them says the crop was
        # placed correctly — not that the screen was reproduced.
        print(f"INFO: {asset_backed} element(s) drawn from a capture crop "
              f"(research-only provenance in assets/manifest.json)")
    if synthesised:
        # Not a detail: these edges pass the functional walk on a target the
        # capture never contained. Reporting the total without them would make
        # "every transition wired" mean less than it appears to.
        print(f"INFO: {len(synthesised)} tap target(s) synthesised at a recorded tap "
              f"point — the label is not in the capture that screen is reproduced "
              f"from: {', '.join(synthesised)}")
    if kept:
        print(f"INFO: kept hand-authored {', '.join(sorted(kept))}")
    if unmeasured:
        # Silence here would look like full coverage; these states have a view
        # name in views.json and no measurement to generate it from.
        print(f"WARN: {len(unmeasured)} mapped state(s) have no measurement: "
              f"{', '.join(unmeasured)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
